name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate stats.svg
        uses: readme-tools/github-readme-stats-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&include_all_commits=true&count_private=true&theme=dracula
          path: dist/stats.svg

      - name: Deploy to stats-output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: stats-output
          publish_dir: dist
